// import jsPDF from "jspdf";

// interface GenerateCertificateProps {
//   studentName: string;
//   courseName: string;
//   completionDate: string;
// }

// export const generateCertificate = ({
//   studentName,
//   courseName,
//   completionDate,
// }: GenerateCertificateProps) => {
//   const doc = new jsPDF("landscape", "mm", "a4");

//   const pageWidth = 297;
//   const pageHeight = 210;

//   // Background color
//   doc.setFillColor("#fcfafa");
//   doc.rect(0, 0, pageWidth, pageHeight, "F");

//   // Elegant gold top & bottom line
//   doc.setDrawColor("#D4AF37"); // Gold color
//   doc.setLineWidth(1.2);
//   doc.line(20, 15, pageWidth - 20, 15);
//   doc.line(20, pageHeight - 15, pageWidth - 20, pageHeight - 15);

//   // Watermark (soft & stylish)
//   doc.setFont("times", "italic");
//   doc.setFontSize(70);
//   doc.setTextColor(240, 240, 240);
//   doc.text("LearnifyHub", pageWidth / 2, pageHeight / 2, {
//     align: "center",
//     rotate: 30, // ✅ FIXED: Correct rotation syntax
//   });

//   // Heading
//   doc.setFont("helvetica", "bold");
//   doc.setFontSize(40);
//   doc.setTextColor("#122f5d");
//   doc.text("Certificate of Completion", pageWidth / 2, 50, {
//     align: "center",
//   });

//   // Thin underline
//   doc.setDrawColor("#D4AF37");
//   doc.setLineWidth(0.7);
//   doc.line(pageWidth / 2 - 70, 55, pageWidth / 2 + 70, 55);

//   // Sub-header
//   doc.setFont("helvetica", "italic");
//   doc.setFontSize(20);
//   doc.setTextColor("#444");
//   doc.text("This is to proudly present to", pageWidth / 2, 80, {
//     align: "center",
//   });

//   // Student name (stylish)
//   doc.setFont("times", "bolditalic");
//   doc.setFontSize(36);
//   doc.setTextColor("#2c3e50");
//   doc.text(studentName, pageWidth / 2, 105, { align: "center" });

//   // Course text
//   doc.setFont("helvetica", "normal");
//   doc.setFontSize(18);
//   doc.setTextColor("#555");
//   doc.text("for the successful completion of", pageWidth / 2, 125, {
//     align: "center",
//   });

//   // Course name (bold, serif)
//   doc.setFont("times", "bold");
//   doc.setFontSize(26);
//   doc.setTextColor("#0f4c81");
//   doc.text(courseName, pageWidth / 2, 145, { align: "center" });

//   // Completion Date
//   doc.setFont("helvetica", "italic");
//   doc.setFontSize(14);
//   doc.setTextColor("#666");
//   doc.text(`Completed on: ${completionDate}`, 20, pageHeight - 35);

//   // Certificate ID
//   doc.setFontSize(12);
//   doc.setTextColor("#888");
//   doc.text(`Certificate ID: LH-${Date.now()}`, 20, pageHeight - 26);

//   // Signature
//   doc.setDrawColor("#333");
//   doc.setLineWidth(0.4);
//   doc.line(pageWidth - 80, pageHeight - 40, pageWidth - 30, pageHeight - 40);
//   doc.setFont("helvetica", "italic");
//   doc.setFontSize(12);
//   doc.setTextColor("#333");
//   doc.text("Authorized Signature", pageWidth - 55, pageHeight - 32, {
//     align: "center",
//   });

//   // Footer
//   doc.setFont("helvetica", "italic");
//   doc.setFontSize(10);
//   doc.setTextColor("#aaa");
//   doc.text("This certificate is generated by LearnifyHub LMS", pageWidth / 2, pageHeight - 10, {
//     align: "center",
//   });

//   doc.save(`${studentName}-Certificate.pdf`);
// };
import jsPDF from "jspdf";

interface GenerateCertificateProps {
  studentName: string;
  courseName: string;
  completionDate: string;
}

export const generateCertificate = ({
  studentName,
  courseName,
  completionDate,
}: GenerateCertificateProps) => {
  const doc = new jsPDF("landscape", "mm", "a4");

  const pageWidth = 297;
  const pageHeight = 210;

  // Soft warm ivory background
  doc.setFillColor("#fdfcf9");
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Delicate top & bottom lines (brushed gold)
  doc.setDrawColor("#c5a663");
  doc.setLineWidth(1);
  doc.line(20, 15, pageWidth - 20, 15);
  doc.line(20, pageHeight - 15, pageWidth - 20, pageHeight - 15);

  // Watermark: subtle large text
  doc.setFont("times", "italic");
  doc.setFontSize(60);
  doc.setTextColor(240, 240, 240);
  doc.text("LearnifyHub", pageWidth / 2, pageHeight / 2, {
    align: "center",
    rotate: 30,
  });

  // Title
  doc.setFont("times", "bold");
  doc.setFontSize(42);
  doc.setTextColor("#2d4059");
  doc.text("Certificate of Completion", pageWidth / 2, 50, {
    align: "center",
  });

  // Small elegant divider
  doc.setDrawColor("#c5a663");
  doc.setLineWidth(0.4);
  doc.line(pageWidth / 2 - 50, 57, pageWidth / 2 + 50, 57);

  // Presented to:
  doc.setFont("helvetica", "normal");
  doc.setFontSize(18);
  doc.setTextColor("#555");
  doc.text("Presented to", pageWidth / 2, 80, { align: "center" });

  // Student name in large serif font
  doc.setFont("times", "bolditalic");
  doc.setFontSize(34);
  doc.setTextColor("#2d4059");
  doc.text(studentName, pageWidth / 2, 100, { align: "center" });

  // For completing the course
  doc.setFont("helvetica", "normal");
  doc.setFontSize(16);
  doc.setTextColor("#555");
  doc.text("for successfully completing the course", pageWidth / 2, 120, {
    align: "center",
  });

  // Course name in contrasting color
  doc.setFont("times", "bold");
  doc.setFontSize(28);
  doc.setTextColor("#c27803");
  doc.text(courseName, pageWidth / 2, 140, { align: "center" });

  // Completion date at bottom left
  doc.setFont("helvetica", "italic");
  doc.setFontSize(12);
  doc.setTextColor("#777");
  doc.text(`Date: ${completionDate}`, 20, pageHeight - 30);

  // Certificate number bottom left
  doc.setFontSize(10);
  doc.text(`Cert ID: LH-${Date.now()}`, 20, pageHeight - 22);

  // Signature line
  doc.setLineWidth(0.5);
  doc.setDrawColor("#333");
  doc.line(pageWidth - 80, pageHeight - 45, pageWidth - 30, pageHeight - 45);

  doc.setFont("helvetica", "italic");
  doc.setFontSize(11);
  doc.setTextColor("#333");
  doc.text("Authorized Signature", pageWidth - 55, pageHeight - 37, {
    align: "center",
  });

  // Small footer line
  doc.setFont("courier", "italic");
  doc.setFontSize(9);
  doc.setTextColor("#aaa");
  doc.text("This certificate is auto-generated by LearnifyHub LMS", pageWidth / 2, pageHeight - 10, {
    align: "center",
  });

  doc.save(`${studentName}-LearnifyHub-Certificate.pdf`);
};
